# Generated by Django 6.1 on 2026-08-24 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Login",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=15)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("source", models.CharField(max_length=100)),
                ("course_interested", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("contacted", "Contacted"),
                            ("interested", "Interested"),
                            ("follow_up", "Follow Up"),
                            ("converted", "Converted"),
                            ("not_interested", "Not Interested"),
                            ("lost", "Lost"),
                        ],
                        default="new",
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_leads",
                        to="app.login",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FollowUp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("follow_up_type", models.CharField(max_length=100)),
                ("remarks", models.TextField(blank=True)),
                ("next_follow_up_date", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="follow_ups",
                        to="app.lead",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="follow_ups",
                        to="app.login",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Conversion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("converted_date", models.DateTimeField(auto_now_add=True)),
                ("course", models.CharField(max_length=100)),
                ("remarks", models.TextField(blank=True)),
                (
                    "lead",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversion",
                        to="app.lead",
                    ),
                ),
                (
                    "converted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conversions",
                        to="app.login",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Call",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "call_type",
                    models.CharField(
                        choices=[("incoming", "Incoming"), ("outgoing", "Outgoing")],
                        default="outgoing",
                        max_length=20,
                    ),
                ),
                ("call_datetime", models.DateTimeField(auto_now_add=True)),
                ("duration", models.PositiveIntegerField(default=0)),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("connected", "Connected"),
                            ("not_connected", "Not Connected"),
                            ("busy", "Busy"),
                            ("interested", "Interested"),
                            ("not_interested", "Not Interested"),
                        ],
                        max_length=30,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calls",
                        to="app.lead",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calls",
                        to="app.login",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NewEmployee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("employee_id", models.CharField(max_length=20, unique=True)),
                ("full_name", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=15)),
                ("department", models.CharField(max_length=100)),
                ("designation", models.CharField(max_length=100)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("employee", "Employee"),
                            ("manager", "Manager"),
                            ("admin", "Admin"),
                        ],
                        default="employee",
                        max_length=20,
                    ),
                ),
                ("joining_date", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "login",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee_profile",
                        to="app.login",
                    ),
                ),
            ],
        ),
    ]
