# Generated by Django 6.1 on 2026-08-26 13:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversion",
            name="course",
            field=models.CharField(
                max_length=100,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Course name contains invalid characters.",
                        regex="^[A-Za-z0-9 .&+-]+$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="followup",
            name="follow_up_type",
            field=models.CharField(
                max_length=100,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Follow-up type should contain only alphabets and spaces.",
                        regex="^[A-Za-z ]+$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="name",
            field=models.CharField(
                max_length=100,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Name should contain only alphabets and spaces.",
                        regex="^[A-Za-z ]+$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="phone",
            field=models.CharField(
                max_length=10,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must contain exactly 10 digits.",
                        regex="^[0-9]{10}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="login",
            name="password",
            field=models.CharField(
                max_length=128,
                validators=[
                    django.core.validators.MinLengthValidator(
                        8, message="Password must be at least 8 characters long."
                    ),
                    django.core.validators.RegexValidator(
                        message="Password must contain at least one letter and one number.",
                        regex="^(?=.*[A-Za-z])(?=.*\\d).+$",
                    ),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="newemployee",
            name="department",
            field=models.CharField(
                max_length=100,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Department should contain only alphabets and spaces.",
                        regex="^[A-Za-z ]+$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="newemployee",
            name="designation",
            field=models.CharField(
                max_length=100,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Designation should contain only alphabets and spaces.",
                        regex="^[A-Za-z ]+$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="newemployee",
            name="employee_id",
            field=models.CharField(
                max_length=20,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Employee ID can contain only letters, numbers, hyphen and underscore.",
                        regex="^[A-Za-z0-9_-]+$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="newemployee",
            name="full_name",
            field=models.CharField(
                max_length=100,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Full name should contain only alphabets and spaces.",
                        regex="^[A-Za-z ]+$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="newemployee",
            name="phone",
            field=models.CharField(
                max_length=10,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must contain exactly 10 digits.",
                        regex="^[0-9]{10}$",
                    )
                ],
            ),
        ),
    ]
