# Generated by Django 6.1 on 2026-09-03 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_conversion_course_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="login",
            name="email",
            field=models.EmailField(max_length=254),
        ),
    ]
