# Generated by Django 6.1.1 on 2026-09-23 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_login_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newemployee",
            name="login",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employee_profile",
                to="app.login",
            ),
        ),
    ]
